[build]
# The index HTML file to drive the bundling process.
target = "web/index.html"
# The output dir for all final assets.
dist = "dist"

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = ["src"]
